// Code generated by goctl. DO NOT EDIT.
package types

type IdReq struct {
	Id int64 `json:"id" path:"id"`
}

type PageReq struct {
	Page int `json:"page" path:"page" form:"page"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterReq struct {
	Username  string `json:"username"`
	Password1 string `json:"password1"`
	Password2 string `json:"password2"`
}

type UserInfoReq struct {
	Id       int64  `json:"id"`
	Username string `json:"username"` // 账户
	Name     string `json:"name"`     // 姓名
	Gender   int64  `json:"gender"`   // 性别
	Phone    string `json:"phone"`    // 手机号
	Avatar   string `json:"avatar"`   // 头像url
	Intro    string `json:"intro"`    // 个人简介
	Location string `json:"location"` // 住址
}
