// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	atcl "go-go-zero/service/file/cmd/api/internal/handler/atcl"
	avatar "go-go-zero/service/file/cmd/api/internal/handler/avatar"
	cmdty "go-go-zero/service/file/cmd/api/internal/handler/cmdty"
	"go-go-zero/service/file/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: avatar.UploadHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/",
					Handler: avatar.CheckHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/file/avatar"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: atcl.UploadHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: atcl.RemoveHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/",
					Handler: atcl.CheckHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/file/atcl"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: cmdty.UploadHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: cmdty.RemoveHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/",
					Handler: cmdty.CheckHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/file/cmdty"),
	)
}
