// Code generated by goctl. DO NOT EDIT.
// Source: file.proto

package server

import (
	"context"

	"go-go-zero/service/file/cmd/rpc/internal/logic"
	"go-go-zero/service/file/cmd/rpc/internal/svc"
	"go-go-zero/service/file/cmd/rpc/types"
)

type FileServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedFileServiceServer
}

func NewFileServiceServer(svcCtx *svc.ServiceContext) *FileServiceServer {
	return &FileServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FileServiceServer) GetCmdtyPicsByOrder(ctx context.Context, in *__.CmdtyPicsReq) (*__.CmdtyPicsResp, error) {
	l := logic.NewGetCmdtyPicsByOrderLogic(ctx, s.svcCtx)
	return l.GetCmdtyPicsByOrder(in)
}
