// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	like "go-go-zero/service/atcl/cmd/api/internal/handler/like"
	"go-go-zero/service/atcl/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: like.LikeHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/id",
					Handler: like.UnlikeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/atcl/like"),
	)
}
