// Code generated by goctl. DO NOT EDIT.
// Source: atcl.proto

package server

import (
	"context"

	"go-go-zero/service/atcl/cmd/rpc/internal/logic"
	"go-go-zero/service/atcl/cmd/rpc/internal/svc"
	"go-go-zero/service/atcl/cmd/rpc/types"
)

type AtclServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedAtclServiceServer
}

func NewAtclServiceServer(svcCtx *svc.ServiceContext) *AtclServiceServer {
	return &AtclServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AtclServiceServer) UpdateCover(ctx context.Context, in *__.CoverReq) (*__.CodeResp, error) {
	l := logic.NewUpdateCoverLogic(ctx, s.svcCtx)
	return l.UpdateCover(in)
}
