// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userDormFieldNames          = builder.RawFieldNames(&UserDorm{})
	userDormRows                = strings.Join(userDormFieldNames, ",")
	userDormRowsExpectAutoSet   = strings.Join(stringx.Remove(userDormFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userDormRowsWithPlaceHolder = strings.Join(stringx.Remove(userDormFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userDormModel interface {
		Insert(ctx context.Context, data *UserDorm) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserDorm, error)
		Update(ctx context.Context, data *UserDorm) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserDormModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserDorm struct {
		Id       int64     `db:"id"`        // id
		Name     string    `db:"name"`      // 地址名
		CreateBy time.Time `db:"create_by"` // 管理员的id
		CreateAt time.Time `db:"create_at"` // 创建时间
		UpdateBy time.Time `db:"update_by"` // 管理员的id
		UpdateAt time.Time `db:"update_at"` // 更新时间
	}
)

func newUserDormModel(conn sqlx.SqlConn) *defaultUserDormModel {
	return &defaultUserDormModel{
		conn:  conn,
		table: "`user_dorm`",
	}
}

func (m *defaultUserDormModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserDormModel) FindOne(ctx context.Context, id int64) (*UserDorm, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userDormRows, m.table)
	var resp UserDorm
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserDormModel) Insert(ctx context.Context, data *UserDorm) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, userDormRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.CreateBy, data.UpdateBy)
	return ret, err
}

func (m *defaultUserDormModel) Update(ctx context.Context, data *UserDorm) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userDormRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.CreateBy, data.UpdateBy, data.Id)
	return err
}

func (m *defaultUserDormModel) tableName() string {
	return m.table
}
