// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userOptFieldNames          = builder.RawFieldNames(&UserOpt{})
	userOptRows                = strings.Join(userOptFieldNames, ",")
	userOptRowsExpectAutoSet   = strings.Join(stringx.Remove(userOptFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userOptRowsWithPlaceHolder = strings.Join(stringx.Remove(userOptFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userOptModel interface {
		Insert(ctx context.Context, data *UserOpt) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserOpt, error)
		Update(ctx context.Context, data *UserOpt) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserOptModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserOpt struct {
		Id       int64  `db:"id"`
		Username string `db:"username"`
		Password string `db:"password"`
		Name     string `db:"name"`
		Status   int64  `db:"status"`
		Level    int64  `db:"level"`
	}
)

func newUserOptModel(conn sqlx.SqlConn) *defaultUserOptModel {
	return &defaultUserOptModel{
		conn:  conn,
		table: "`user_opt`",
	}
}

func (m *defaultUserOptModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserOptModel) FindOne(ctx context.Context, id int64) (*UserOpt, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userOptRows, m.table)
	var resp UserOpt
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserOptModel) Insert(ctx context.Context, data *UserOpt) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, userOptRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Username, data.Password, data.Name, data.Status, data.Level)
	return ret, err
}

func (m *defaultUserOptModel) Update(ctx context.Context, data *UserOpt) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userOptRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Username, data.Password, data.Name, data.Status, data.Level, data.Id)
	return err
}

func (m *defaultUserOptModel) tableName() string {
	return m.table
}
