// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	msg "go-go-zero/service/chat/cmd/api/internal/handler/msg"
	room "go-go-zero/service/chat/cmd/api/internal/handler/room"
	"go-go-zero/service/chat/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: room.CreateRoomHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: room.ChatHandler(serverCtx),
			},
		},
		rest.WithPrefix("/chat/room"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: msg.ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/chat/msg"),
	)
}
