// Code generated by goctl. DO NOT EDIT.
package types

type IdReq struct {
	Id int64 `json:"id" path:"id" form:"id"`
}

type IdStatusReq struct {
	Id     int64 `json:"id" path:"id" form:"id"`
	Status int8  `json:"status" path:"status" form:"status"`
}

type TradeIdReq struct {
	TradeId int64 `json:"tradeId" path:"tradeId"`
}

type UserIdReq struct {
	UserId int64 `form:"userId"`
}

type IdDoneReq struct {
	Id   int64 `form:"id"`
	Done int   `form:"done"`
}

type RoleReq struct {
	Role int `path:"role"`
}

type CmtReq struct {
	TradeId  int64  `json:"tradeId"`
	UserId   int64  `json:"userId"`
	Name     string `json:"name"`
	ToUserId int64  `json:"toUserId"`
	Type     int    `json:"type"`
	Content  string `json:"content"`
}

type TradeReq struct {
	OwnerId int64   `json:"ownerId"`
	Owner   string  `json:"owner"`
	OtherId int64   `json:"otherId"`
	Other   string  `json:"other"`
	CmdtyId int64   `json:"cmdtyId"`
	Payment float64 `json:"payment"`
	Type    int8    `json:"type"`
}
