// Code generated by goctl. DO NOT EDIT.
package types

type IdReq struct {
	Id int64 `json:"id" path:"id" form:"id"`
}

type TradeIdReq struct {
	TradeId int64 `json:"tradeId" path:"tradeId"`
}

type UserIdReq struct {
	UserId int64 `form:"userId"`
}

type IdDoneReq struct {
	Id   int64 `form:"id"`
	Done int   `form:"done"`
}

type TypeReq struct {
	Type int `path:"type"`
}

type CmtReq struct {
	TradeId  int64  `json:"tradeId"`
	UserId   int64  `json:"userId"`
	ToUserId int64  `json:"toUserId"`
	Type     int    `json:"type"`
	Content  string `json:"content"`
}
