// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	collect "go-go-zero/service/cmdty/cmd/api/internal/handler/collect"
	"go-go-zero/service/cmdty/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: collect.CollectHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: collect.UncollectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: collect.ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/cmdty/collect"),
	)
}
