// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	cinfo "go-go-zero/service/cmdty/cmd/api/internal/handler/cinfo"
	collect "go-go-zero/service/cmdty/cmd/api/internal/handler/collect"
	"go-go-zero/service/cmdty/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: cinfo.GetByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: cinfo.ListByUidAndOptionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sellsave",
				Handler: cinfo.SellsaveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sellpublish",
				Handler: cinfo.SellpublishHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/wantsave",
				Handler: cinfo.WantsaveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/wantpublish",
				Handler: cinfo.WantpublishHandler(serverCtx),
			},
		},
		rest.WithPrefix("/cmdty"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: collect.CollectHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: collect.UncollectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: collect.ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/cmdty/collect"),
	)
}
