// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	cinfo "go-go-zero/service/cmdty/cmd/api/internal/handler/cinfo"
	cmt "go-go-zero/service/cmdty/cmd/api/internal/handler/cmt"
	collect "go-go-zero/service/cmdty/cmd/api/internal/handler/collect"
	history "go-go-zero/service/cmdty/cmd/api/internal/handler/history"
	tag "go-go-zero/service/cmdty/cmd/api/internal/handler/tag"
	"go-go-zero/service/cmdty/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: cinfo.GetByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: cinfo.ListByUidAndOptionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sellsave",
				Handler: cinfo.SellsaveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sellpublish",
				Handler: cinfo.SellpublishHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/wantsave",
				Handler: cinfo.WantsaveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/wantpublish",
				Handler: cinfo.WantpublishHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/cache",
				Handler: cinfo.ListCacheByTypeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/cmdty"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: collect.CollectHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: collect.UncollectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: collect.ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/cmdty/collect"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: tag.ListTagHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/",
				Handler: tag.RemoveTagHandler(serverCtx),
			},
		},
		rest.WithPrefix("/cmdty/tag"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: history.ListHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/",
				Handler: history.RemoveHistoryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/cmdty/history"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: cmt.CmtHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:cmdtyId",
				Handler: cmt.ListByInfoIdHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: cmt.RemoveCmtHandler(serverCtx),
			},
		},
		rest.WithPrefix("/cmdty/cmt"),
	)
}
