// Code generated by goctl. DO NOT EDIT.
package types

type IdReq struct {
	Id int64 `json:"id" path:"id"`
}

type CreateRoomReq struct {
	Buyer    string `json:"buyer"`
	BuyerId  int64  `json:"buyerId"`
	CmdtyId  int64  `json:"cmdtyId"` // 对应的商品信息
	Cover    string `json:"cover"`
	Seller   string `json:"seller"`
	SellerId int64  `json:"sellerId"`
}

type ListMessageReq struct {
	Id   int64 `form:"id"`
	Page int64 `form:"page"`
}

type IdResp struct {
	Id int64 `json:"id"`
}

type ChatMessageResp struct {
	Id       int64  `json:"id"` // bigint自增
	Content  string `json:"content"`
	RoomId   int64  `json:"roomId"`
	Time     string `json:"time"`
	ToUserId int64  `json:"toUserId"`
	UserId   int64  `json:"userId"`
}
