// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cmdtyTagFieldNames          = builder.RawFieldNames(&CmdtyTag{})
	cmdtyTagRows                = strings.Join(cmdtyTagFieldNames, ",")
	cmdtyTagRowsExpectAutoSet   = strings.Join(stringx.Remove(cmdtyTagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cmdtyTagRowsWithPlaceHolder = strings.Join(stringx.Remove(cmdtyTagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	cmdtyTagModel interface {
		Insert(ctx context.Context, data *CmdtyTag) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CmdtyTag, error)
		Update(ctx context.Context, data *CmdtyTag) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCmdtyTagModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CmdtyTag struct {
		Id       int64     `db:"id"`        // 分类ID编号
		Name     string    `db:"name"`      // 分类名称
		CreateBy int64     `db:"create_by"` // 管理员的id
		CreateAt time.Time `db:"create_at"` // 创建时间
		UpdateBy int64     `db:"update_by"` // 管理员的id
		UpdateAt time.Time `db:"update_at"` // 更新时间
	}
)

func newCmdtyTagModel(conn sqlx.SqlConn) *defaultCmdtyTagModel {
	return &defaultCmdtyTagModel{
		conn:  conn,
		table: "`cmdty_tag`",
	}
}

func (m *defaultCmdtyTagModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCmdtyTagModel) FindOne(ctx context.Context, id int64) (*CmdtyTag, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cmdtyTagRows, m.table)
	var resp CmdtyTag
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCmdtyTagModel) Insert(ctx context.Context, data *CmdtyTag) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, cmdtyTagRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.CreateBy, data.UpdateBy)
	return ret, err
}

func (m *defaultCmdtyTagModel) Update(ctx context.Context, data *CmdtyTag) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cmdtyTagRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.CreateBy, data.UpdateBy, data.Id)
	return err
}

func (m *defaultCmdtyTagModel) tableName() string {
	return m.table
}
