// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cmdtyCollectFieldNames          = builder.RawFieldNames(&CmdtyCollect{})
	cmdtyCollectRows                = strings.Join(cmdtyCollectFieldNames, ",")
	cmdtyCollectRowsExpectAutoSet   = strings.Join(stringx.Remove(cmdtyCollectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cmdtyCollectRowsWithPlaceHolder = strings.Join(stringx.Remove(cmdtyCollectFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	cmdtyCollectModel interface {
		Insert(ctx context.Context, data *CmdtyCollect) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CmdtyCollect, error)
		Update(ctx context.Context, data *CmdtyCollect) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCmdtyCollectModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CmdtyCollect struct {
		Id       int64     `db:"id"`        // id
		UserId   int64     `db:"user_id"`   // 用户id
		CmdtyId  int64     `db:"cmdty_id"`  // 商品id
		Status   int64     `db:"status"`    // 1存在，0失效
		CreateAt time.Time `db:"create_at"` // 创建时间
	}
)

func newCmdtyCollectModel(conn sqlx.SqlConn) *defaultCmdtyCollectModel {
	return &defaultCmdtyCollectModel{
		conn:  conn,
		table: "`cmdty_collect`",
	}
}

func (m *defaultCmdtyCollectModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCmdtyCollectModel) FindOne(ctx context.Context, id int64) (*CmdtyCollect, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cmdtyCollectRows, m.table)
	var resp CmdtyCollect
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCmdtyCollectModel) Insert(ctx context.Context, data *CmdtyCollect) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, cmdtyCollectRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.CmdtyId, data.Status)
	return ret, err
}

func (m *defaultCmdtyCollectModel) Update(ctx context.Context, data *CmdtyCollect) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cmdtyCollectRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.CmdtyId, data.Status, data.Id)
	return err
}

func (m *defaultCmdtyCollectModel) tableName() string {
	return m.table
}
