// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cmdtyDoneFieldNames          = builder.RawFieldNames(&CmdtyDone{})
	cmdtyDoneRows                = strings.Join(cmdtyDoneFieldNames, ",")
	cmdtyDoneRowsExpectAutoSet   = strings.Join(stringx.Remove(cmdtyDoneFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cmdtyDoneRowsWithPlaceHolder = strings.Join(stringx.Remove(cmdtyDoneFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	cmdtyDoneModel interface {
		Insert(ctx context.Context, data *CmdtyDone) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CmdtyDone, error)
		Update(ctx context.Context, data *CmdtyDone) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCmdtyDoneModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CmdtyDone struct {
		Id        int64     `db:"id"`         // id
		UserId    int64     `db:"user_id"`    // 用户id
		Cover     string    `db:"cover"`      // 封面图片
		Tag       string    `db:"tag"`        // 分类名
		Price     float64   `db:"price"`      // 商品价格
		Brand     string    `db:"brand"`      // 品牌
		Model     string    `db:"model"`      // 型号
		Intro     string    `db:"intro"`      // 商品介绍
		PublishAt time.Time `db:"publish_at"` // 发布时间
		View      int64     `db:"view"`       // 查看数量
		Collect   int64     `db:"collect"`    // 收藏数
		Type      int64     `db:"type"`       // 1为售卖商品，2为收商品
		Like      int64     `db:"like"`       // 点赞数
	}
)

func newCmdtyDoneModel(conn sqlx.SqlConn) *defaultCmdtyDoneModel {
	return &defaultCmdtyDoneModel{
		conn:  conn,
		table: "`cmdty_done`",
	}
}

func (m *defaultCmdtyDoneModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCmdtyDoneModel) FindOne(ctx context.Context, id int64) (*CmdtyDone, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cmdtyDoneRows, m.table)
	var resp CmdtyDone
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCmdtyDoneModel) Insert(ctx context.Context, data *CmdtyDone) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, cmdtyDoneRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Cover, data.Tag, data.Price, data.Brand, data.Model, data.Intro, data.PublishAt, data.View, data.Collect, data.Type, data.Like)
	return ret, err
}

func (m *defaultCmdtyDoneModel) Update(ctx context.Context, data *CmdtyDone) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cmdtyDoneRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Cover, data.Tag, data.Price, data.Brand, data.Model, data.Intro, data.PublishAt, data.View, data.Collect, data.Type, data.Like, data.Id)
	return err
}

func (m *defaultCmdtyDoneModel) tableName() string {
	return m.table
}
