// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cmdtyCmtFieldNames          = builder.RawFieldNames(&CmdtyCmt{})
	cmdtyCmtRows                = strings.Join(cmdtyCmtFieldNames, ",")
	cmdtyCmtRowsExpectAutoSet   = strings.Join(stringx.Remove(cmdtyCmtFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cmdtyCmtRowsWithPlaceHolder = strings.Join(stringx.Remove(cmdtyCmtFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	cmdtyCmtModel interface {
		Insert(ctx context.Context, data *CmdtyCmt) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CmdtyCmt, error)
		Update(ctx context.Context, data *CmdtyCmt) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCmdtyCmtModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CmdtyCmt struct {
		Id       int64     `db:"id"`         // id
		CmdtyId  int64     `db:"cmdty_id"`   // 对应的商品id
		UserId   int64     `db:"user_id"`    // 留言的用户id
		Content  string    `db:"content"`    // 留言内容
		RootId   int64     `db:"root_id"`    // 根留言
		ToUserId int64     `db:"to_user_id"` // 回复给到用户
		CreateAt time.Time `db:"create_at"`  // 评论时间
	}
)

func newCmdtyCmtModel(conn sqlx.SqlConn) *defaultCmdtyCmtModel {
	return &defaultCmdtyCmtModel{
		conn:  conn,
		table: "`cmdty_cmt`",
	}
}

func (m *defaultCmdtyCmtModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCmdtyCmtModel) FindOne(ctx context.Context, id int64) (*CmdtyCmt, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", cmdtyCmtRows, m.table)
	var resp CmdtyCmt
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCmdtyCmtModel) Insert(ctx context.Context, data *CmdtyCmt) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, cmdtyCmtRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CmdtyId, data.UserId, data.Content, data.RootId, data.ToUserId)
	return ret, err
}

func (m *defaultCmdtyCmtModel) Update(ctx context.Context, data *CmdtyCmt) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, cmdtyCmtRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CmdtyId, data.UserId, data.Content, data.RootId, data.ToUserId, data.Id)
	return err
}

func (m *defaultCmdtyCmtModel) tableName() string {
	return m.table
}
