// Code generated by goctl. DO NOT EDIT.
package types

type IdReq struct {
	Id int64 `json:"id"`
}

type BaseResp struct {
	Code int8   `json:"code"`
	Msg  string `json:"msg"`
}

type CollectResponse struct {
	Id       int64   `json:"id"`
	UserId   int64   `json:"userId"`
	CmdtyId  int64   `json:"cmdtyId"`
	Cover    string  `json:"cover"`
	Price    float64 `json:"price"`
	Status   int64   `json:"status"`
	CreateAt string  `json:"createAt"`
}
