// Code generated by goctl. DO NOT EDIT.
// Source: atcl.proto

package atclservice

import (
	"context"

	"go-go-zero/service/atcl/cmd/rpc/types"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CodeResp = __.CodeResp
	CoverReq = __.CoverReq

	AtclService interface {
		UpdateCover(ctx context.Context, in *CoverReq, opts ...grpc.CallOption) (*CodeResp, error)
	}

	defaultAtclService struct {
		cli zrpc.Client
	}
)

func NewAtclService(cli zrpc.Client) AtclService {
	return &defaultAtclService{
		cli: cli,
	}
}

func (m *defaultAtclService) UpdateCover(ctx context.Context, in *CoverReq, opts ...grpc.CallOption) (*CodeResp, error) {
	client := __.NewAtclServiceClient(m.cli.Conn())
	return client.UpdateCover(ctx, in, opts...)
}
