// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	fileAvatarFieldNames          = builder.RawFieldNames(&FileAvatar{})
	fileAvatarRows                = strings.Join(fileAvatarFieldNames, ",")
	fileAvatarRowsExpectAutoSet   = strings.Join(stringx.Remove(fileAvatarFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	fileAvatarRowsWithPlaceHolder = strings.Join(stringx.Remove(fileAvatarFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	fileAvatarModel interface {
		Insert(ctx context.Context, data *FileAvatar) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*FileAvatar, error)
		Update(ctx context.Context, data *FileAvatar) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFileAvatarModel struct {
		conn  sqlx.SqlConn
		table string
	}

	FileAvatar struct {
		Id         int64     `db:"id"`
		UserId     int64     `db:"user_id"`
		Url        string    `db:"url"`
		ObjectName string    `db:"objectName"`
		UploadAt   time.Time `db:"upload_at"`
	}
)

func newFileAvatarModel(conn sqlx.SqlConn) *defaultFileAvatarModel {
	return &defaultFileAvatarModel{
		conn:  conn,
		table: "`file_avatar`",
	}
}

func (m *defaultFileAvatarModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFileAvatarModel) FindOne(ctx context.Context, id int64) (*FileAvatar, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", fileAvatarRows, m.table)
	var resp FileAvatar
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFileAvatarModel) Insert(ctx context.Context, data *FileAvatar) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, fileAvatarRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Url, data.ObjectName, data.UploadAt)
	return ret, err
}

func (m *defaultFileAvatarModel) Update(ctx context.Context, data *FileAvatar) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, fileAvatarRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Url, data.ObjectName, data.UploadAt, data.Id)
	return err
}

func (m *defaultFileAvatarModel) tableName() string {
	return m.table
}
