// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: atcl.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AtclService_UpdateCover_FullMethodName = "/user.AtclService/UpdateCover"
)

// AtclServiceClient is the client API for AtclService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AtclServiceClient interface {
	UpdateCover(ctx context.Context, in *CoverReq, opts ...grpc.CallOption) (*CodeResp, error)
}

type atclServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAtclServiceClient(cc grpc.ClientConnInterface) AtclServiceClient {
	return &atclServiceClient{cc}
}

func (c *atclServiceClient) UpdateCover(ctx context.Context, in *CoverReq, opts ...grpc.CallOption) (*CodeResp, error) {
	out := new(CodeResp)
	err := c.cc.Invoke(ctx, AtclService_UpdateCover_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AtclServiceServer is the server API for AtclService service.
// All implementations must embed UnimplementedAtclServiceServer
// for forward compatibility
type AtclServiceServer interface {
	UpdateCover(context.Context, *CoverReq) (*CodeResp, error)
	mustEmbedUnimplementedAtclServiceServer()
}

// UnimplementedAtclServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAtclServiceServer struct {
}

func (UnimplementedAtclServiceServer) UpdateCover(context.Context, *CoverReq) (*CodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCover not implemented")
}
func (UnimplementedAtclServiceServer) mustEmbedUnimplementedAtclServiceServer() {}

// UnsafeAtclServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AtclServiceServer will
// result in compilation errors.
type UnsafeAtclServiceServer interface {
	mustEmbedUnimplementedAtclServiceServer()
}

func RegisterAtclServiceServer(s grpc.ServiceRegistrar, srv AtclServiceServer) {
	s.RegisterService(&AtclService_ServiceDesc, srv)
}

func _AtclService_UpdateCover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AtclServiceServer).UpdateCover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AtclService_UpdateCover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AtclServiceServer).UpdateCover(ctx, req.(*CoverReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AtclService_ServiceDesc is the grpc.ServiceDesc for AtclService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AtclService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.AtclService",
	HandlerType: (*AtclServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateCover",
			Handler:    _AtclService_UpdateCover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atcl.proto",
}
