// Code generated by goctl. DO NOT EDIT.
package types

type IdReq struct {
	Id int64 `json:"id" path:"id"`
}

type IdsReq struct {
	Ids []int64 `json:"ids"`
}

type AvatarReq struct {
	Avatar []byte `json:"avatar"`
}

type PicReq struct {
	Pic   []byte `json:"pic"`
	Order int64  `json:"order"`
}

type CmdtyPicsReq struct {
	CmdtyId int64    `json:"cmdtyId"`
	Pics    []PicReq `json:"pics"`
}

type AtclPicsReq struct {
	AtclId int64    `json:"atclId"`
	Pics   []PicReq `json:"pics"`
}

type AvatarResp struct {
	Url string `json:"url"`
}

type PicResp struct {
	Id    int64  `json:"id"`
	Url   string `json:"url"`
	Order int64  `json:"order"`
}
