// Code generated by goctl. DO NOT EDIT.
package types

type IdReq struct {
	Id int64 `json:"id" path:"id"`
}

type IdsReq struct {
	Ids []int64 `json:"ids"`
}

type AvatarReq struct {
	Avatar []byte `json:"avatar"`
}

type AvatarResp struct {
	Url string `json:"url"`
}

type PicResp struct {
	Id    int64  `json:"id"`
	Url   string `json:"url"`
	Order int64  `json:"order"`
}
