// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tradeDoneFieldNames          = builder.RawFieldNames(&TradeDone{})
	tradeDoneRows                = strings.Join(tradeDoneFieldNames, ",")
	tradeDoneRowsExpectAutoSet   = strings.Join(stringx.Remove(tradeDoneFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tradeDoneRowsWithPlaceHolder = strings.Join(stringx.Remove(tradeDoneFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tradeDoneModel interface {
		Insert(ctx context.Context, data *TradeDone) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TradeDone, error)
		Update(ctx context.Context, data *TradeDone) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTradeDoneModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TradeDone struct {
		Id           int64     `db:"id"`          // id
		BuyerId      int64     `db:"buyer_id"`    // 卖家id
		Buyer        string    `db:"buyer"`       // 卖家名
		SellerId     int64     `db:"seller_id"`   // 买家id
		Seller       string    `db:"seller"`      // 买家名
		CmdtyId      int64     `db:"cmdty_id"`    // 商品id
		BriefIntro   string    `db:"brief_intro"` // 商品名
		Cover        string    `db:"cover"`
		Location     string    `db:"location"`
		Payment      float64   `db:"payment"`
		SellerDoneAt time.Time `db:"seller_done_at"`
		BuyerDoneAt  time.Time `db:"buyer_done_at"`
		DoneAt       time.Time `db:"done_at"` // 创建时间
	}
)

func newTradeDoneModel(conn sqlx.SqlConn) *defaultTradeDoneModel {
	return &defaultTradeDoneModel{
		conn:  conn,
		table: "`trade_done`",
	}
}

func (m *defaultTradeDoneModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTradeDoneModel) FindOne(ctx context.Context, id int64) (*TradeDone, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tradeDoneRows, m.table)
	var resp TradeDone
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTradeDoneModel) Insert(ctx context.Context, data *TradeDone) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tradeDoneRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.BuyerId, data.Buyer, data.SellerId, data.Seller, data.CmdtyId, data.BriefIntro, data.Cover, data.Location, data.Payment, data.SellerDoneAt, data.BuyerDoneAt, data.DoneAt)
	return ret, err
}

func (m *defaultTradeDoneModel) Update(ctx context.Context, data *TradeDone) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tradeDoneRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.BuyerId, data.Buyer, data.SellerId, data.Seller, data.CmdtyId, data.BriefIntro, data.Cover, data.Location, data.Payment, data.SellerDoneAt, data.BuyerDoneAt, data.DoneAt, data.Id)
	return err
}

func (m *defaultTradeDoneModel) tableName() string {
	return m.table
}
